name: backend CI

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: | 
          docker-compose -f ./.docker/docker-compose.yml build
          docker-compose -f ./.docker/docker-compose.yml up -d
          cd ./backend
          yarn install
          yarn lint
          yarn test:unit
          yarn test:integration
